version: '3.8'


services:
  web:
    build: 
      context: .
      dockerfile: ./docker/local/django/Dockerfile
    container_name: raffle_django_app
    command: /start
    volumes:
      - .:/raffle_app
      - static_files:/raffle_app/staticfiles
    # ports:
    #   - 8080:8000
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - db
      - redis

  nginx:
    build:
      context: ./nginx/
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - static_files:/home/app/staticfiles
      
  dns:
    build:
      context: ./dns/
    restart: always
    ports:
      - 53:53
      - 53:53/udp
    volumes:
      - ./dns/named.conf:/etc/bind/named.conf
      - ./dns/zone/:/etc/bind/zone/
    command: named -c /etc/bind/named.conf -g -u named

  # Database Postgres
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    container_name: raffle_postgres_db
    ports:
      - 5432:5432

  redis:
    image: redis:6-alpine
    container_name: raffle_django_redis


  celery_worker:
    restart: always
    build: 
      context: .
      dockerfile: ./docker/local/django/Dockerfile
    command: /start-celeryworker
    container_name: raffle-celery-worker
    volumes:
      - .:/raffle_app
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - web

  celery_beat:
    build:
      context: .
      dockerfile: ./docker/local/django/Dockerfile
    command: /start-celerybeat
    container_name: raffle-celery-beat
    volumes:
      - .:/raffle_app
    env_file:
      - .env
    depends_on:
      - redis
      - db

  flower:
    build:
      context: .
      dockerfile: ./docker/local/django/Dockerfile
    command: /start-flower
    container_name: raffle-celery-flower
    volumes:
      - .:/raffle_app
    env_file:
      - .env
    ports:
      - 5557:5555
    depends_on:
      - redis
      - db
    

volumes:
  postgres_data:
  static_files:
