apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-beat
spec:
  selector:
    matchLabels:
      app: celery-beat
  template:
    metadata:
      labels:
        app: celery-beat
    spec:
      containers:
      - name: celery-beat
        image: gyasi_ecom:v2
        imagePullPolicy: Never
        # command: ['celery', '-A', 'kubernetes_django', 'beat', '-l', 'DEBUG']
        command: ["/bin/bash", "/start-celerybeat"]
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: gyasi-postgres-credentials
                key: user
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: gyasi-postgres-credentials
                key: password
          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                name: gyasi-config
                key: gyasi_db_host
          - name: REDIS_HOST
            valueFrom:
              configMapKeyRef:
                name: gyasi-config
                key: gyasi_redis_host
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
