apiVersion: v1
kind: PersistentVolume
metadata:
  name: gyasi-postgres-pv
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: manual
  hostPath:
    path: /data/postgres-pv