apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gyasi-postgres-pvc
  labels:
    type: local
spec:
  storageClassName: manual
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  volumeName: gyasi-postgres-pv