apiVersion: apps/v1
kind: Deployment
metadata:
  name: gyasi-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gyasi-redis
  template:
    metadata:
      labels:
        app: gyasi-redis
    spec:
      containers:
      - name: gyasi-redis
        image: redis
        resources:
          limits:
            memory: 128Mi
            cpu: 100m
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379


