#!/bin/bash

set -o errexit
set -o nounset

worker_ready() {
    celery -A gyasi_ecommerce inspect ping
}

until worker_ready; do
  >&2 echo 'Celery workers not available'
  sleep 1
done
>&2 echo 'Celery workers is available'

# celery -A elevate  \
#     --broker="${CELERY_BROKER}" \
#     flower

celery -A gyasi_ecommerce --broker="${CELERY_BROKER}"// flower