apiVersion: v1
kind: Secret
metadata:
  name: gyasi-postgres-credentials
type: Opaque
data:
  user: YWRtaW4K
  password: YWRtaW4xMjMK

---

apiVersion: v1
kind: Service
metadata:
  name: gyasi-postgres-service
spec:
  selector:
    app: gyasi-postgres-service
  ports:
  - port: 5432
    targetPort: 5432

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: gyasi-postgres-pv
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: manual
  hostPath:
    path: /data/postgres-pv

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gyasi-postgres-pvc
  labels:
    type: local
spec:
  storageClassName: manual
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  volumeName: gyasi-postgres-pv

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gyasi-postgres-container
  template:
    metadata:
      labels:
        app: gyasi-postgres-container
        tier: backend
    spec:
      containers:
        - name: gyasi-postgres-container
          image: postgres:13
          resources:
            limits:
              memory: 128Mi
              cpu: 100m
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: gyasi-postgres-credentials
                  key: user

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gyasi-postgres-credentials
                  key: password

            - name: POSTGRES_DB
              value: GyasiDB

          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-volume-mount
              mountPath: /var/lib/postgresql/data

      volumes:
        - name: postgres-volume-mount
          persistentVolumeClaim:
            claimName: gyasi-postgres-pvc



