# Generated by Django 4.1.6 on 2023-02-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_site", "0002_salesmodel_cart_paid_productmodel_actual_price_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SalesModel",
        ),
        migrations.AddField(
            model_name="ticketmodel",
            name="is_winner",
            field=models.BooleanField(default=False),
        ),
    ]
