apiVersion: v1
kind: Service
metadata:
  name: gyasi-app-service
spec:
  type: LoadBalancer
  selector:
    app: gyasi-app
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    nodePort: 30000