apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gyasi-postgres-container
  template:
    metadata:
      labels:
        app: gyasi-postgres-container
        tier: backend
    spec:
      containers:
        - name: gyasi-postgres-container
          image: postgres:13
          resources:
            limits:
              memory: 128Mi
              cpu: 100m
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: gyasi-postgres-credentials
                  key: user
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: gyasi-postgres-credentials
                  key: name
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gyasi-postgres-credentials
                  key: password
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-volume-mount
              mountPath: /var/lib/postgresql/data

      volumes:
        - name: postgres-volume-mount
          persistentVolumeClaim:
            claimName: gyasi-postgres-pvc



